name: test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.3', '7.4']
    steps:
      - uses: actions/checkout@v2
      - name: Install Composer dependencies
        run: composer install
      - name: Run unit tests
        run: php${{ matrix.php }} vendor/bin/phpunit
      - name: Check coding style
        run: php${{ matrix.php }} vendor/bin/phpcs --standard=PSR12 src/
